/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.16
 * Generated at: 2022-12-30 00:30:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.arthe.apiservlet.webapp.headers.models.Categoria;
import java.util.List;
import java.util.Map;
import com.arthe.apiservlet.webapp.headers.models.Producto;
import java.time.format.DateTimeFormatter;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.arthe.apiservlet.webapp.headers.models.Categoria");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.time.format.DateTimeFormatter");
    _jspx_imports_classes.add("com.arthe.apiservlet.webapp.headers.models.Producto");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

  List<Categoria> categorias = (List<Categoria>) request.getAttribute("categorias");
  Map<String ,String> errores = (Map<String, String>) request.getAttribute("errores");
  Producto producto = (Producto) request.getAttribute("producto");
  String fecha = producto.getFechaRegistro() != null ?
           producto.getFechaRegistro().format(DateTimeFormatter.ofPattern("yyyy-MM-dd")) : "";

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"es\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\"\r\n");
      out.write("        content=\"width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"ie=edge\">\r\n");
      out.write("  <title>Formulario Producto</title>\r\n");
      out.write("</head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <h1>Formulario Producto</h1>\r\n");
      out.write("    <form action=\"");
      out.print(request.getContextPath());
      out.write("/productos/form\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <label for=\"nombre\">Nombre</label>\r\n");
      out.write("        <div>\r\n");
      out.write("          <input type=\"text\" name=\"nombre\" id=\"nombre\" value=\"");
      out.print(producto.getNombre() != null ? producto.getNombre() : "");
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (errores != null && errores.containsKey("nombre")){
      out.write("\r\n");
      out.write("          <di style=\"color:red;\">\r\n");
      out.write("            ");
      out.print(errores.get("nombre"));
      out.write("\r\n");
      out.write("          </di>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <label for=\"precio\">Precio</label>\r\n");
      out.write("        <div>\r\n");
      out.write("          <input type=\"number\" name=\"precio\" id=\"precio\" value=\"");
      out.print(producto.getPrecio() != 0 ? producto.getPrecio() : "");
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (errores != null && errores.containsKey("precio")){
      out.write("\r\n");
      out.write("        <di style=\"color:red;\">\r\n");
      out.write("          ");
      out.print(errores.get("precio"));
      out.write("\r\n");
      out.write("        </di>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <label for=\"sku\">Sku</label>\r\n");
      out.write("        <div>\r\n");
      out.write("          <input type=\"text\" name=\"sku\" id=\"sku\" value=\"");
      out.print(producto.getSku() != null ? producto.getSku() : "");
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (errores != null && errores.containsKey("sku")){
      out.write("\r\n");
      out.write("        <di style=\"color:red;\">\r\n");
      out.write("          ");
      out.print(errores.get("sku"));
      out.write("\r\n");
      out.write("        </di>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <label for=\"fecha_registro\">Fecha Registro</label>\r\n");
      out.write("        <div>\r\n");
      out.write("          <input type=\"date\" name=\"fecha_registro\" id=\"fecha_registro\" value=\"");
      out.print(fecha);
      out.write("\">\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (errores != null && errores.containsKey("fecha_registro")){
      out.write("\r\n");
      out.write("        <di style=\"color:red;\">\r\n");
      out.write("          ");
      out.print(errores.get("fecha_registro"));
      out.write("\r\n");
      out.write("        </di>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div>\r\n");
      out.write("        <label for=\"categoria\">Categoria</label>\r\n");
      out.write("        <div>\r\n");
      out.write("          <select name=\"categoria\" id=\"categoria\">\r\n");
      out.write("            <option value=\"\">-- Seleccionar --</option>\r\n");
      out.write("            ");
 for (Categoria c : categorias){
      out.write("\r\n");
      out.write("              <option value=\"");
      out.print(c.getId());
      out.write('"');
      out.write(' ');
      out.print(c.getId().equals(producto.getCategoria().getId()) ? "selected" : "");
      out.write(' ');
      out.write('>');
      out.print(c.getNombre());
      out.write("</option>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("          </select>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
 if (errores != null && errores.containsKey("categoria")){
      out.write("\r\n");
      out.write("        <di style=\"color:red;\">\r\n");
      out.write("          ");
      out.print(errores.get("categoria"));
      out.write("\r\n");
      out.write("        </di>\r\n");
      out.write("        ");
}
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div><input type=\"submit\" value=\"");
      out.print((producto.getId()!=null && producto.getId() > 0) ? "Editar" : " Crear" );
      out.write("\"></div>\r\n");
      out.write("      <input type=\"hidden\" name=\"id\" value=\"");
      out.print(producto.getId());
      out.write("\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
